#!/bin/bash
# shell script called by SMF to run a Hudson swarm client as a service.
# placed in /lib/svc/method
vmopts="$(svcprop -p hudson/jvm_options $SMF_FMRI)"
opts="$(svcprop -p hudson/options $SMF_FMRI)"
exec java $vmopts -jar /usr/local/bin/hudson-swarm-client.jar $opts
